# NumPy Assignment

Total Points: 30 [+ 10 Bonus]

Total Number of Questions: 3

In [1]:
# imports

import numpy as np
from random import shuffle


## Question 1

#### Points: 15 (5 + 2.5 + 2.5)

**Q.** Write functions for the following sub tasks:

**Q 1.1.** Given a numpy array of shape `(n, n)` and an index ```i, j```, find the [cofactor](https://www.cuemath.com/algebra/minor-of-matrix/) of the element at index ```(i, j)```.

**Note:** use only slices and indexing to solve this question.

**Q 1.2.** Given a numpy array of shape `(n, n)` find the [determinant](https://www.cuemath.com/algebra/determinant-of-matrix/) of the matrix.

**Q 1.3.** Given a numpy array of shape `(n, n)` find the [inverse](https://www.cuemath.com/algebra/inverse-of-matrix/) of the matrix.

In [2]:
# Q 1.2

def determinant(array):
    return np.linalg.det(array)

In [3]:
# Q 1.1

def cofactor(array, i, j):
    # using slices and single for loop
    new = np.zeros((array.shape[0] - 1, array.shape[1] - 1))

    # count is the index (of rows) of the new array
    count = 0
    
    for x in range(array.shape[0]):
        # removing ith row
        if x != i:
            # removing jth column
            new[count, :] = np.array(list(array[x, :j]) + list(array[x, j+1:]))
            count += 1
        
    # or you can use numpy.concatenate()/stack functions to avoid converting to a list
    return ((-1)**(i+j))*determinant(new)

# since you've completed the assignment, another method using slices and selection based on condition

def cofactor2(array, i, j):
    mask = np.ones(array.shape, dtype = bool)
    # removing the ith row and jth column
    mask[i, :] = False
    mask[:, j] = False
    selected = array[mask].reshape(array.shape[0] - 1, array.shape[1] - 1)
    return ((-1)**(i+j))*determinant(selected)

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(cofactor(arr, 1, 1))
print(cofactor2(arr, 1, 1))

-12.0
-12.0


In [5]:
# Q 1.3
def inverse(array):
    return np.linalg.inv(array)

## Question 2

#### Points: 10 [+ 5 Bonus]

Q. Write a function that given a 2 dimensional array of numbers, returns another 2 dimensional array, such that:

i) Every alternate row (starting from row 0) is reversed.

ii) In the new array, all positive elements are replaced by their square-roots and all negative elements are replaced by their squares.

Example:

Input:

```python
[[1, -4, 7],
[2, 11, -3],
[5, -8, 9]]
```

Output:

```python
array([[ 2.64575131, 16.        ,  1.        ],
       [ 1.41421356,  3.31662479,  9.        ],
       [ 3.        , 64.        ,  2.23606798]])
```



Note: Do not modify the original array

Try solving it once with and once without [```numpy.vectorize()```](https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html)


#### Points Distribution:

- 7 points for a correct solution, satisfying all requirements/conditions

- 3 points if solution uses (or) an additional solution using ```np.vectorize()```

- Bonus points (+ 5): Read up [selection based on condition](https://thispointer.com/python-numpy-select-elements-or-indices-by-conditions-from-numpy-array/), and try solving the question using this, without nested loops.

In [6]:
def soln2(array):
    # you can use len(array) or array.shape[0], and len(array[0]) or array.shape[1] interchangebly
    new = np.zeros((len(array), len(array[0])))
    for i in range(len(array)):
        if i % 2 == 0:
            new[i] = array[i][::-1]
        else:
            new[i] = array[i]
        for j in range(len(new[0])):
            if new[i][j] >= 0:
                new[i][j] = np.sqrt(new[i][j])
            else:
                new[i][j] = array[i][j]**2
    return new

In [7]:
def change(x):
    if x >= 0:
        return np.sqrt(x)
    else:
        return x**2
    
def soln1_using_vectorize(array):
    new = np.zeros((len(array), len(array[0])))
    for i in range(len(array)):
        if i % 2 == 0:
            new[i] = array[i][::-1]
        else:
            new[i] = array[i]
    return np.vectorize(change)(new)

In [8]:
def soln2_using_selection(array):
    new = np.zeros((len(array), len(array)))
    new[::2] = [i[::-1]for i in array[::2]]
    new[1::2] = array[1::2]
    new[new>=0] = np.sqrt(new[new>=0])
    new[new<0] = new[new<0]**2
    return new

In [9]:
arr = np.array([[1, -4, 7], [2, 11, -3], [5, -8, 9]])

print(soln2(arr), soln1_using_vectorize(arr), soln2_using_selection(arr), sep = "\n\n")

[[ 2.64575131 16.          1.        ]
 [ 1.41421356  3.31662479  9.        ]
 [ 3.         64.          2.23606798]]

[[ 2.64575131 16.          1.        ]
 [ 1.41421356  3.31662479  9.        ]
 [ 3.         64.          2.23606798]]

[[ 2.64575131 16.          1.        ]
 [ 1.41421356  3.31662479  9.        ]
 [ 3.         64.          2.23606798]]


## Question 3

#### Points: 10 [+ 5 Bonus]

Q. Write a function that given a number  ```n```, returns a 2 dimensional array of size ```n x n``` with the following pattern:

i) Contains elements from 1 to n^2

ii) ```n``` groups/rows are ordered taken in sets, ```1...n```,  ```n+1...2n```,  ```2n+1...3n```, and so on.

ii) All ```n``` rows are shuffled randomly, while order of elements in each row is maintained.

Example:

Input:

```python
n = 3
```


Output: (as its randomized, every run will result in a different output)

```python
[[7, 8, 9],
 [1, 2, 3],
 [4, 5, 6]]
```

**Hint:** Search the docs for [```np.random```](https://numpy.org/doc/stable/reference/random/index.html) to find some functions that might help you solve this problem in a simple and easy.

#### Points Distribution:

- 10 points for a correct solution, satisfying all requirements/conditions

- Bonus points (+5): For finding more than one function in ```np.random``` to solve this, and mention the difference(s) between the methods.

**Note:** It is not necessary to use the functions in ```np.random``` to solve this problem, and it reccomnended to solve the problem once with and without using ```np.random```. (**Hint:** you can still use the standard python libraries like ```random``` to solve this)



In [10]:
def soln3(n):
    arr = np.arange(1, n**2 + 1).reshape(n, n)
    index_arr = list(range(n))
    shuffle(index_arr)
    new = np.zeros((n, n))
    for i in range(n):
        new[i] = arr[index_arr[i]]
        # note: we're not using shuffle(arr) directly here, as it might give the same row twice.
    return new

In [11]:
def soln3_using_permutation(n):
    rng = np.random.default_rng()
    arr = np.arange(1, n**2 + 1).reshape(n, n)
    return rng.permutation(arr)

    # Legacy/RandomState method:
    # arr = np.arange(1, n**2 + 1).reshape(n, n)
    # return np.random.permutation(arr)

In [12]:
def soln3_using_shuffle(n):
    rng = np.random.default_rng()
    arr = np.arange(1, n**2 + 1).reshape(n, n)
    rng.shuffle(arr)
    # Legacy/RandomState method:
    # arr = np.arange(1, n**2 + 1).reshape(n, n)
    # np.random.shuffle(arr)
    return arr 

In [13]:
print(soln3(3), soln3_using_permutation(3), soln3_using_shuffle(3), sep = "\n\n")

[[7. 8. 9.]
 [1. 2. 3.]
 [4. 5. 6.]]

[[4 5 6]
 [1 2 3]
 [7 8 9]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]


Difference between the two methods is:

- ```permutation``` returns a new array with randomly permuted/shuffled rows/elements, leaving the original array unchanged.
- ```shuffle``` randomly shuffles the rows of original array (i.e., it changes the original array), and returns ```None```.